### ISSUE TITLE
patcore 模型结果异常

### ISSUE THREAD

**Issue by hengyanchen** [NagatoYuki0943/anomalib-tensorrt-cpp#5]
原模型结果正常，onnx可视化看了下也是正常的，大佬看下可能是什么问题呢
![000](https://github.com/NagatoYuki0943/anomalib-tensorrt-cpp/assets/76552951/e988d706-d42b-41cb-b1c7-ef742e926df6)

**Comment by NagatoYuki0943** [comment]
patchcore模型训练配置文件调整center_crop为 `center_crop: null`
就是只缩放图片，不再剪裁图片，这个你设置了吗？

**Comment by hengyanchen** [comment]
> patchcore模型训练配置文件调整center_crop为 `center_crop: null` 就是只缩放图片，不再剪裁图片，这个你设置了吗？

哦哦，确实没有，谢谢，我试试
